application:
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: application/static
- url: /.*
  script: application.app
  login: admin

libraries:
- name: jinja2
  version: "2.6"
